os:
- osx
- linux
language: go
sudo: false
go:
- 1.4.2
- 1.5
install:
- go get -u -t simonwaldherr.de/go/cgolGo
script:
- $HOME/gopath/bin/cgolGo -d 100
notifications:
  email:
    recipients:
    - travis@simon.waldherr.eu
    on_success: always
    on_failure: always
